// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const deleteQuestion = `-- name: DeleteQuestion :exec
DELETE FROM questions WHERE id = $1
`

func (q *Queries) DeleteQuestion(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteQuestion, id)
	return err
}

const setRoleByEmail = `-- name: SetRoleByEmail :exec
UPDATE users SET role = $2 WHERE email = $1
`

type SetRoleByEmailParams struct {
	Email *string `json:"email"`
	Role  string  `json:"role"`
}

func (q *Queries) SetRoleByEmail(ctx context.Context, arg SetRoleByEmailParams) error {
	_, err := q.db.Exec(ctx, setRoleByEmail, arg.Email, arg.Role)
	return err
}
