// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: leaderboard.sql

package store

import (
	"context"
)

const globalLeaderboard = `-- name: GlobalLeaderboard :many
SELECT u.username, COALESCE(SUM(gr.score),0)::double precision AS total_score,
       COUNT(*)::int AS games, COALESCE(SUM(gr.correct_cnt),0)::int AS correct
FROM game_results gr JOIN users u ON u.id = gr.user_id
WHERE u.username IS NOT NULL
GROUP BY u.id, u.username
ORDER BY total_score DESC
LIMIT 20
`

type GlobalLeaderboardRow struct {
	Username   *string `json:"username"`
	TotalScore float64 `json:"total_score"`
	Games      int32   `json:"games"`
	Correct    int32   `json:"correct"`
}

// Global reyting — faqat akkauntlar (mehmonlar emas), umumiy ball bo'yicha top 20.
func (q *Queries) GlobalLeaderboard(ctx context.Context) ([]GlobalLeaderboardRow, error) {
	rows, err := q.db.Query(ctx, globalLeaderboard)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GlobalLeaderboardRow
	for rows.Next() {
		var i GlobalLeaderboardRow
		if err := rows.Scan(
			&i.Username,
			&i.TotalScore,
			&i.Games,
			&i.Correct,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
