// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mastery.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const getMastery = `-- name: GetMastery :one
SELECT user_id, category_id, mastery, attempts, updated_at FROM user_mastery WHERE user_id = $1 AND category_id = $2
`

type GetMasteryParams struct {
	UserID     uuid.UUID `json:"user_id"`
	CategoryID uuid.UUID `json:"category_id"`
}

func (q *Queries) GetMastery(ctx context.Context, arg GetMasteryParams) (UserMastery, error) {
	row := q.db.QueryRow(ctx, getMastery, arg.UserID, arg.CategoryID)
	var i UserMastery
	err := row.Scan(
		&i.UserID,
		&i.CategoryID,
		&i.Mastery,
		&i.Attempts,
		&i.UpdatedAt,
	)
	return i, err
}

const getQuestionByID = `-- name: GetQuestionByID :one
SELECT id, category_id, type, prompt, options, correct, accept, media_url, explanation, difficulty, meta, created_at FROM questions WHERE id = $1
`

func (q *Queries) GetQuestionByID(ctx context.Context, id uuid.UUID) (Question, error) {
	row := q.db.QueryRow(ctx, getQuestionByID, id)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Type,
		&i.Prompt,
		&i.Options,
		&i.Correct,
		&i.Accept,
		&i.MediaUrl,
		&i.Explanation,
		&i.Difficulty,
		&i.Meta,
		&i.CreatedAt,
	)
	return i, err
}

const listMasteryByUser = `-- name: ListMasteryByUser :many
SELECT um.mastery, um.attempts,
       c.slug AS category_slug, c.name AS category_name,
       s.slug AS subject_slug, s.name AS subject_name
FROM user_mastery um
JOIN categories c ON c.id = um.category_id
JOIN subjects s ON s.id = c.subject_id
WHERE um.user_id = $1
ORDER BY s.name, c.name
`

type ListMasteryByUserRow struct {
	Mastery      float64 `json:"mastery"`
	Attempts     int32   `json:"attempts"`
	CategorySlug string  `json:"category_slug"`
	CategoryName string  `json:"category_name"`
	SubjectSlug  string  `json:"subject_slug"`
	SubjectName  string  `json:"subject_name"`
}

func (q *Queries) ListMasteryByUser(ctx context.Context, userID uuid.UUID) ([]ListMasteryByUserRow, error) {
	rows, err := q.db.Query(ctx, listMasteryByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMasteryByUserRow
	for rows.Next() {
		var i ListMasteryByUserRow
		if err := rows.Scan(
			&i.Mastery,
			&i.Attempts,
			&i.CategorySlug,
			&i.CategoryName,
			&i.SubjectSlug,
			&i.SubjectName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertMastery = `-- name: UpsertMastery :exec
INSERT INTO user_mastery (user_id, category_id, mastery, attempts, updated_at)
VALUES ($1, $2, $3, $4, now())
ON CONFLICT (user_id, category_id)
DO UPDATE SET mastery = EXCLUDED.mastery, attempts = EXCLUDED.attempts, updated_at = now()
`

type UpsertMasteryParams struct {
	UserID     uuid.UUID `json:"user_id"`
	CategoryID uuid.UUID `json:"category_id"`
	Mastery    float64   `json:"mastery"`
	Attempts   int32     `json:"attempts"`
}

func (q *Queries) UpsertMastery(ctx context.Context, arg UpsertMasteryParams) error {
	_, err := q.db.Exec(ctx, upsertMastery,
		arg.UserID,
		arg.CategoryID,
		arg.Mastery,
		arg.Attempts,
	)
	return err
}
