// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"time"

	"github.com/google/uuid"
)

type AnswersLog struct {
	ID         uuid.UUID `json:"id"`
	SessionID  uuid.UUID `json:"session_id"`
	UserID     uuid.UUID `json:"user_id"`
	QuestionID uuid.UUID `json:"question_id"`
	Given      []byte    `json:"given"`
	IsCorrect  bool      `json:"is_correct"`
	TimeMs     int32     `json:"time_ms"`
	CreatedAt  time.Time `json:"created_at"`
}

type Category struct {
	ID        uuid.UUID `json:"id"`
	SubjectID uuid.UUID `json:"subject_id"`
	Slug      string    `json:"slug"`
	Name      string    `json:"name"`
}

type GameResult struct {
	ID         uuid.UUID `json:"id"`
	SessionID  uuid.UUID `json:"session_id"`
	UserID     uuid.UUID `json:"user_id"`
	Score      float64   `json:"score"`
	CorrectCnt int32     `json:"correct_cnt"`
	Rank       *int32    `json:"rank"`
}

type GameSession struct {
	ID            uuid.UUID  `json:"id"`
	Code          string     `json:"code"`
	HostUserID    uuid.UUID  `json:"host_user_id"`
	SubjectID     uuid.UUID  `json:"subject_id"`
	CategoryID    *uuid.UUID `json:"category_id"`
	Mode          string     `json:"mode"`
	Opponent      string     `json:"opponent"`
	QuestionCount int32      `json:"question_count"`
	TimePerQ      int32      `json:"time_per_q"`
	Status        string     `json:"status"`
	StartedAt     *time.Time `json:"started_at"`
	FinishedAt    *time.Time `json:"finished_at"`
	CreatedAt     time.Time  `json:"created_at"`
}

type Question struct {
	ID          uuid.UUID `json:"id"`
	CategoryID  uuid.UUID `json:"category_id"`
	Type        string    `json:"type"`
	Prompt      string    `json:"prompt"`
	Options     []byte    `json:"options"`
	Correct     []byte    `json:"correct"`
	Accept      []byte    `json:"accept"`
	MediaUrl    *string   `json:"media_url"`
	Explanation *string   `json:"explanation"`
	Difficulty  int16     `json:"difficulty"`
	Meta        []byte    `json:"meta"`
	CreatedAt   time.Time `json:"created_at"`
}

type SrsCard struct {
	UserID       uuid.UUID  `json:"user_id"`
	QuestionID   uuid.UUID  `json:"question_id"`
	Ease         float64    `json:"ease"`
	IntervalDays int32      `json:"interval_days"`
	Repetitions  int32      `json:"repetitions"`
	DueAt        time.Time  `json:"due_at"`
	LastReviewed *time.Time `json:"last_reviewed"`
}

type Subject struct {
	ID   uuid.UUID `json:"id"`
	Slug string    `json:"slug"`
	Name string    `json:"name"`
	Icon *string   `json:"icon"`
}

type Tournament struct {
	ID            uuid.UUID `json:"id"`
	Title         string    `json:"title"`
	SubjectID     uuid.UUID `json:"subject_id"`
	QuestionCount int32     `json:"question_count"`
	StartsAt      time.Time `json:"starts_at"`
	EndsAt        time.Time `json:"ends_at"`
	CreatedAt     time.Time `json:"created_at"`
}

type TournamentEntry struct {
	TournamentID uuid.UUID `json:"tournament_id"`
	UserID       uuid.UUID `json:"user_id"`
	Score        int32     `json:"score"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type User struct {
	ID           uuid.UUID `json:"id"`
	Username     *string   `json:"username"`
	Email        *string   `json:"email"`
	PasswordHash *string   `json:"password_hash"`
	TelegramID   *int64    `json:"telegram_id"`
	IsGuest      bool      `json:"is_guest"`
	Role         string    `json:"role"`
	CreatedAt    time.Time `json:"created_at"`
}

type UserMastery struct {
	UserID     uuid.UUID `json:"user_id"`
	CategoryID uuid.UUID `json:"category_id"`
	Mastery    float64   `json:"mastery"`
	Attempts   int32     `json:"attempts"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type UserRating struct {
	UserID    uuid.UUID `json:"user_id"`
	SubjectID uuid.UUID `json:"subject_id"`
	Rating    int32     `json:"rating"`
	Games     int32     `json:"games"`
	UpdatedAt time.Time `json:"updated_at"`
}
