// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: questions.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const countQuestionsByCategory = `-- name: CountQuestionsByCategory :one
SELECT count(*) FROM questions WHERE category_id = $1
`

func (q *Queries) CountQuestionsByCategory(ctx context.Context, categoryID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countQuestionsByCategory, categoryID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createQuestion = `-- name: CreateQuestion :one
INSERT INTO questions (
    category_id, type, prompt, options, correct, accept, media_url, explanation, difficulty, meta
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, category_id, type, prompt, options, correct, accept, media_url, explanation, difficulty, meta, created_at
`

type CreateQuestionParams struct {
	CategoryID  uuid.UUID `json:"category_id"`
	Type        string    `json:"type"`
	Prompt      string    `json:"prompt"`
	Options     []byte    `json:"options"`
	Correct     []byte    `json:"correct"`
	Accept      []byte    `json:"accept"`
	MediaUrl    *string   `json:"media_url"`
	Explanation *string   `json:"explanation"`
	Difficulty  int16     `json:"difficulty"`
	Meta        []byte    `json:"meta"`
}

func (q *Queries) CreateQuestion(ctx context.Context, arg CreateQuestionParams) (Question, error) {
	row := q.db.QueryRow(ctx, createQuestion,
		arg.CategoryID,
		arg.Type,
		arg.Prompt,
		arg.Options,
		arg.Correct,
		arg.Accept,
		arg.MediaUrl,
		arg.Explanation,
		arg.Difficulty,
		arg.Meta,
	)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Type,
		&i.Prompt,
		&i.Options,
		&i.Correct,
		&i.Accept,
		&i.MediaUrl,
		&i.Explanation,
		&i.Difficulty,
		&i.Meta,
		&i.CreatedAt,
	)
	return i, err
}

const getQuestionInSubject = `-- name: GetQuestionInSubject :one
SELECT q.id, q.category_id, q.type, q.prompt, q.options, q.correct, q.accept, q.media_url, q.explanation, q.difficulty, q.meta, q.created_at FROM questions q
JOIN categories c ON c.id = q.category_id
WHERE q.id = $1 AND c.subject_id = $2
`

type GetQuestionInSubjectParams struct {
	ID        uuid.UUID `json:"id"`
	SubjectID uuid.UUID `json:"subject_id"`
}

func (q *Queries) GetQuestionInSubject(ctx context.Context, arg GetQuestionInSubjectParams) (Question, error) {
	row := q.db.QueryRow(ctx, getQuestionInSubject, arg.ID, arg.SubjectID)
	var i Question
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.Type,
		&i.Prompt,
		&i.Options,
		&i.Correct,
		&i.Accept,
		&i.MediaUrl,
		&i.Explanation,
		&i.Difficulty,
		&i.Meta,
		&i.CreatedAt,
	)
	return i, err
}

const listQuestionsByCategory = `-- name: ListQuestionsByCategory :many
SELECT id, category_id, type, prompt, options, correct, accept, media_url, explanation, difficulty, meta, created_at FROM questions WHERE category_id = $1
`

func (q *Queries) ListQuestionsByCategory(ctx context.Context, categoryID uuid.UUID) ([]Question, error) {
	rows, err := q.db.Query(ctx, listQuestionsByCategory, categoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Question
	for rows.Next() {
		var i Question
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Type,
			&i.Prompt,
			&i.Options,
			&i.Correct,
			&i.Accept,
			&i.MediaUrl,
			&i.Explanation,
			&i.Difficulty,
			&i.Meta,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const randomQuestionsByCategory = `-- name: RandomQuestionsByCategory :many
SELECT id, category_id, type, prompt, options, correct, accept, media_url, explanation, difficulty, meta, created_at FROM questions
WHERE category_id = $1
ORDER BY random()
LIMIT $2
`

type RandomQuestionsByCategoryParams struct {
	CategoryID uuid.UUID `json:"category_id"`
	Limit      int32     `json:"limit"`
}

func (q *Queries) RandomQuestionsByCategory(ctx context.Context, arg RandomQuestionsByCategoryParams) ([]Question, error) {
	rows, err := q.db.Query(ctx, randomQuestionsByCategory, arg.CategoryID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Question
	for rows.Next() {
		var i Question
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Type,
			&i.Prompt,
			&i.Options,
			&i.Correct,
			&i.Accept,
			&i.MediaUrl,
			&i.Explanation,
			&i.Difficulty,
			&i.Meta,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const randomQuestionsBySubject = `-- name: RandomQuestionsBySubject :many
SELECT q.id, q.category_id, q.type, q.prompt, q.options, q.correct, q.accept, q.media_url, q.explanation, q.difficulty, q.meta, q.created_at FROM questions q
JOIN categories c ON c.id = q.category_id
WHERE c.subject_id = $1
ORDER BY random()
LIMIT $2
`

type RandomQuestionsBySubjectParams struct {
	SubjectID uuid.UUID `json:"subject_id"`
	Limit     int32     `json:"limit"`
}

func (q *Queries) RandomQuestionsBySubject(ctx context.Context, arg RandomQuestionsBySubjectParams) ([]Question, error) {
	rows, err := q.db.Query(ctx, randomQuestionsBySubject, arg.SubjectID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Question
	for rows.Next() {
		var i Question
		if err := rows.Scan(
			&i.ID,
			&i.CategoryID,
			&i.Type,
			&i.Prompt,
			&i.Options,
			&i.Correct,
			&i.Accept,
			&i.MediaUrl,
			&i.Explanation,
			&i.Difficulty,
			&i.Meta,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
