// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: rating.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const getRating = `-- name: GetRating :one
SELECT rating, games FROM user_rating WHERE user_id = $1 AND subject_id = $2
`

type GetRatingParams struct {
	UserID    uuid.UUID `json:"user_id"`
	SubjectID uuid.UUID `json:"subject_id"`
}

type GetRatingRow struct {
	Rating int32 `json:"rating"`
	Games  int32 `json:"games"`
}

func (q *Queries) GetRating(ctx context.Context, arg GetRatingParams) (GetRatingRow, error) {
	row := q.db.QueryRow(ctx, getRating, arg.UserID, arg.SubjectID)
	var i GetRatingRow
	err := row.Scan(&i.Rating, &i.Games)
	return i, err
}

const listRatingsByUser = `-- name: ListRatingsByUser :many
SELECT ur.rating, ur.games, s.slug AS subject_slug, s.name AS subject_name
FROM user_rating ur
JOIN subjects s ON s.id = ur.subject_id
WHERE ur.user_id = $1
ORDER BY ur.rating DESC
`

type ListRatingsByUserRow struct {
	Rating      int32  `json:"rating"`
	Games       int32  `json:"games"`
	SubjectSlug string `json:"subject_slug"`
	SubjectName string `json:"subject_name"`
}

func (q *Queries) ListRatingsByUser(ctx context.Context, userID uuid.UUID) ([]ListRatingsByUserRow, error) {
	rows, err := q.db.Query(ctx, listRatingsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRatingsByUserRow
	for rows.Next() {
		var i ListRatingsByUserRow
		if err := rows.Scan(
			&i.Rating,
			&i.Games,
			&i.SubjectSlug,
			&i.SubjectName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertRating = `-- name: UpsertRating :exec
INSERT INTO user_rating (user_id, subject_id, rating, games)
VALUES ($1, $2, $3, 1)
ON CONFLICT (user_id, subject_id)
DO UPDATE SET rating = EXCLUDED.rating, games = user_rating.games + 1, updated_at = now()
`

type UpsertRatingParams struct {
	UserID    uuid.UUID `json:"user_id"`
	SubjectID uuid.UUID `json:"subject_id"`
	Rating    int32     `json:"rating"`
}

func (q *Queries) UpsertRating(ctx context.Context, arg UpsertRatingParams) error {
	_, err := q.db.Exec(ctx, upsertRating, arg.UserID, arg.SubjectID, arg.Rating)
	return err
}
