// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const createSession = `-- name: CreateSession :one
INSERT INTO game_sessions (
    code, host_user_id, subject_id, category_id, mode, opponent, question_count, time_per_q
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, code, host_user_id, subject_id, category_id, mode, opponent, question_count, time_per_q, status, started_at, finished_at, created_at
`

type CreateSessionParams struct {
	Code          string     `json:"code"`
	HostUserID    uuid.UUID  `json:"host_user_id"`
	SubjectID     uuid.UUID  `json:"subject_id"`
	CategoryID    *uuid.UUID `json:"category_id"`
	Mode          string     `json:"mode"`
	Opponent      string     `json:"opponent"`
	QuestionCount int32      `json:"question_count"`
	TimePerQ      int32      `json:"time_per_q"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (GameSession, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.Code,
		arg.HostUserID,
		arg.SubjectID,
		arg.CategoryID,
		arg.Mode,
		arg.Opponent,
		arg.QuestionCount,
		arg.TimePerQ,
	)
	var i GameSession
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.HostUserID,
		&i.SubjectID,
		&i.CategoryID,
		&i.Mode,
		&i.Opponent,
		&i.QuestionCount,
		&i.TimePerQ,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSessionByCode = `-- name: GetSessionByCode :one
SELECT id, code, host_user_id, subject_id, category_id, mode, opponent, question_count, time_per_q, status, started_at, finished_at, created_at FROM game_sessions WHERE code = $1
`

func (q *Queries) GetSessionByCode(ctx context.Context, code string) (GameSession, error) {
	row := q.db.QueryRow(ctx, getSessionByCode, code)
	var i GameSession
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.HostUserID,
		&i.SubjectID,
		&i.CategoryID,
		&i.Mode,
		&i.Opponent,
		&i.QuestionCount,
		&i.TimePerQ,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT id, code, host_user_id, subject_id, category_id, mode, opponent, question_count, time_per_q, status, started_at, finished_at, created_at FROM game_sessions WHERE id = $1
`

func (q *Queries) GetSessionByID(ctx context.Context, id uuid.UUID) (GameSession, error) {
	row := q.db.QueryRow(ctx, getSessionByID, id)
	var i GameSession
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.HostUserID,
		&i.SubjectID,
		&i.CategoryID,
		&i.Mode,
		&i.Opponent,
		&i.QuestionCount,
		&i.TimePerQ,
		&i.Status,
		&i.StartedAt,
		&i.FinishedAt,
		&i.CreatedAt,
	)
	return i, err
}

const insertAnswerLog = `-- name: InsertAnswerLog :exec
INSERT INTO answers_log (session_id, user_id, question_id, given, is_correct, time_ms)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertAnswerLogParams struct {
	SessionID  uuid.UUID `json:"session_id"`
	UserID     uuid.UUID `json:"user_id"`
	QuestionID uuid.UUID `json:"question_id"`
	Given      []byte    `json:"given"`
	IsCorrect  bool      `json:"is_correct"`
	TimeMs     int32     `json:"time_ms"`
}

func (q *Queries) InsertAnswerLog(ctx context.Context, arg InsertAnswerLogParams) error {
	_, err := q.db.Exec(ctx, insertAnswerLog,
		arg.SessionID,
		arg.UserID,
		arg.QuestionID,
		arg.Given,
		arg.IsCorrect,
		arg.TimeMs,
	)
	return err
}

const listResultsBySession = `-- name: ListResultsBySession :many
SELECT id, session_id, user_id, score, correct_cnt, rank FROM game_results WHERE session_id = $1 ORDER BY rank
`

func (q *Queries) ListResultsBySession(ctx context.Context, sessionID uuid.UUID) ([]GameResult, error) {
	rows, err := q.db.Query(ctx, listResultsBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GameResult
	for rows.Next() {
		var i GameResult
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.UserID,
			&i.Score,
			&i.CorrectCnt,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSessionFinished = `-- name: SetSessionFinished :exec
UPDATE game_sessions SET status = 'finished', finished_at = now() WHERE id = $1
`

func (q *Queries) SetSessionFinished(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, setSessionFinished, id)
	return err
}

const setSessionRunning = `-- name: SetSessionRunning :exec
UPDATE game_sessions SET status = 'running', started_at = now() WHERE id = $1
`

func (q *Queries) SetSessionRunning(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, setSessionRunning, id)
	return err
}

const upsertResult = `-- name: UpsertResult :one
INSERT INTO game_results (session_id, user_id, score, correct_cnt, rank)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (session_id, user_id)
DO UPDATE SET score = EXCLUDED.score, correct_cnt = EXCLUDED.correct_cnt, rank = EXCLUDED.rank
RETURNING id, session_id, user_id, score, correct_cnt, rank
`

type UpsertResultParams struct {
	SessionID  uuid.UUID `json:"session_id"`
	UserID     uuid.UUID `json:"user_id"`
	Score      float64   `json:"score"`
	CorrectCnt int32     `json:"correct_cnt"`
	Rank       *int32    `json:"rank"`
}

func (q *Queries) UpsertResult(ctx context.Context, arg UpsertResultParams) (GameResult, error) {
	row := q.db.QueryRow(ctx, upsertResult,
		arg.SessionID,
		arg.UserID,
		arg.Score,
		arg.CorrectCnt,
		arg.Rank,
	)
	var i GameResult
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.UserID,
		&i.Score,
		&i.CorrectCnt,
		&i.Rank,
	)
	return i, err
}
