// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: srs.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countDueCards = `-- name: CountDueCards :one
SELECT count(*) FROM srs_cards WHERE user_id = $1 AND due_at <= now()
`

func (q *Queries) CountDueCards(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countDueCards, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getDueCards = `-- name: GetDueCards :many
SELECT q.id, q.type, q.prompt, q.options, q.correct, q.explanation
FROM srs_cards s
JOIN questions q ON q.id = s.question_id
JOIN categories c ON c.id = q.category_id
WHERE s.user_id = $1 AND c.subject_id = $2 AND s.due_at <= now()
ORDER BY s.due_at
LIMIT $3
`

type GetDueCardsParams struct {
	UserID    uuid.UUID `json:"user_id"`
	SubjectID uuid.UUID `json:"subject_id"`
	Limit     int32     `json:"limit"`
}

type GetDueCardsRow struct {
	ID          uuid.UUID `json:"id"`
	Type        string    `json:"type"`
	Prompt      string    `json:"prompt"`
	Options     []byte    `json:"options"`
	Correct     []byte    `json:"correct"`
	Explanation *string   `json:"explanation"`
}

func (q *Queries) GetDueCards(ctx context.Context, arg GetDueCardsParams) ([]GetDueCardsRow, error) {
	rows, err := q.db.Query(ctx, getDueCards, arg.UserID, arg.SubjectID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDueCardsRow
	for rows.Next() {
		var i GetDueCardsRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Prompt,
			&i.Options,
			&i.Correct,
			&i.Explanation,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNewQuestions = `-- name: GetNewQuestions :many
SELECT q.id, q.type, q.prompt, q.options, q.correct, q.explanation
FROM questions q
JOIN categories c ON c.id = q.category_id
WHERE c.subject_id = $1
  AND NOT EXISTS (SELECT 1 FROM srs_cards s WHERE s.user_id = $2 AND s.question_id = q.id)
LIMIT $3
`

type GetNewQuestionsParams struct {
	SubjectID uuid.UUID `json:"subject_id"`
	UserID    uuid.UUID `json:"user_id"`
	Limit     int32     `json:"limit"`
}

type GetNewQuestionsRow struct {
	ID          uuid.UUID `json:"id"`
	Type        string    `json:"type"`
	Prompt      string    `json:"prompt"`
	Options     []byte    `json:"options"`
	Correct     []byte    `json:"correct"`
	Explanation *string   `json:"explanation"`
}

func (q *Queries) GetNewQuestions(ctx context.Context, arg GetNewQuestionsParams) ([]GetNewQuestionsRow, error) {
	rows, err := q.db.Query(ctx, getNewQuestions, arg.SubjectID, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetNewQuestionsRow
	for rows.Next() {
		var i GetNewQuestionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Prompt,
			&i.Options,
			&i.Correct,
			&i.Explanation,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSrsCard = `-- name: GetSrsCard :one
SELECT user_id, question_id, ease, interval_days, repetitions, due_at, last_reviewed FROM srs_cards WHERE user_id = $1 AND question_id = $2
`

type GetSrsCardParams struct {
	UserID     uuid.UUID `json:"user_id"`
	QuestionID uuid.UUID `json:"question_id"`
}

func (q *Queries) GetSrsCard(ctx context.Context, arg GetSrsCardParams) (SrsCard, error) {
	row := q.db.QueryRow(ctx, getSrsCard, arg.UserID, arg.QuestionID)
	var i SrsCard
	err := row.Scan(
		&i.UserID,
		&i.QuestionID,
		&i.Ease,
		&i.IntervalDays,
		&i.Repetitions,
		&i.DueAt,
		&i.LastReviewed,
	)
	return i, err
}

const upsertSrsCard = `-- name: UpsertSrsCard :exec
INSERT INTO srs_cards (user_id, question_id, ease, interval_days, repetitions, due_at, last_reviewed)
VALUES ($1, $2, $3, $4, $5, $6, now())
ON CONFLICT (user_id, question_id)
DO UPDATE SET ease = EXCLUDED.ease, interval_days = EXCLUDED.interval_days,
  repetitions = EXCLUDED.repetitions, due_at = EXCLUDED.due_at, last_reviewed = now()
`

type UpsertSrsCardParams struct {
	UserID       uuid.UUID `json:"user_id"`
	QuestionID   uuid.UUID `json:"question_id"`
	Ease         float64   `json:"ease"`
	IntervalDays int32     `json:"interval_days"`
	Repetitions  int32     `json:"repetitions"`
	DueAt        time.Time `json:"due_at"`
}

func (q *Queries) UpsertSrsCard(ctx context.Context, arg UpsertSrsCardParams) error {
	_, err := q.db.Exec(ctx, upsertSrsCard,
		arg.UserID,
		arg.QuestionID,
		arg.Ease,
		arg.IntervalDays,
		arg.Repetitions,
		arg.DueAt,
	)
	return err
}
