// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subjects.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (subject_id, slug, name)
VALUES ($1, $2, $3)
RETURNING id, subject_id, slug, name
`

type CreateCategoryParams struct {
	SubjectID uuid.UUID `json:"subject_id"`
	Slug      string    `json:"slug"`
	Name      string    `json:"name"`
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategory, arg.SubjectID, arg.Slug, arg.Name)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.SubjectID,
		&i.Slug,
		&i.Name,
	)
	return i, err
}

const createSubject = `-- name: CreateSubject :one
INSERT INTO subjects (slug, name, icon)
VALUES ($1, $2, $3)
RETURNING id, slug, name, icon
`

type CreateSubjectParams struct {
	Slug string  `json:"slug"`
	Name string  `json:"name"`
	Icon *string `json:"icon"`
}

func (q *Queries) CreateSubject(ctx context.Context, arg CreateSubjectParams) (Subject, error) {
	row := q.db.QueryRow(ctx, createSubject, arg.Slug, arg.Name, arg.Icon)
	var i Subject
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Icon,
	)
	return i, err
}

const getSubjectBySlug = `-- name: GetSubjectBySlug :one
SELECT id, slug, name, icon FROM subjects WHERE slug = $1
`

func (q *Queries) GetSubjectBySlug(ctx context.Context, slug string) (Subject, error) {
	row := q.db.QueryRow(ctx, getSubjectBySlug, slug)
	var i Subject
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Icon,
	)
	return i, err
}

const listCategoriesBySubject = `-- name: ListCategoriesBySubject :many
SELECT id, subject_id, slug, name FROM categories WHERE subject_id = $1 ORDER BY name
`

func (q *Queries) ListCategoriesBySubject(ctx context.Context, subjectID uuid.UUID) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategoriesBySubject, subjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.SubjectID,
			&i.Slug,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubjects = `-- name: ListSubjects :many
SELECT id, slug, name, icon FROM subjects ORDER BY name
`

func (q *Queries) ListSubjects(ctx context.Context) ([]Subject, error) {
	rows, err := q.db.Query(ctx, listSubjects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Subject
	for rows.Next() {
		var i Subject
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Icon,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
