// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tournaments.sql

package store

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createTournament = `-- name: CreateTournament :one
INSERT INTO tournaments (title, subject_id, question_count, starts_at, ends_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, title, subject_id, question_count, starts_at, ends_at, created_at
`

type CreateTournamentParams struct {
	Title         string    `json:"title"`
	SubjectID     uuid.UUID `json:"subject_id"`
	QuestionCount int32     `json:"question_count"`
	StartsAt      time.Time `json:"starts_at"`
	EndsAt        time.Time `json:"ends_at"`
}

func (q *Queries) CreateTournament(ctx context.Context, arg CreateTournamentParams) (Tournament, error) {
	row := q.db.QueryRow(ctx, createTournament,
		arg.Title,
		arg.SubjectID,
		arg.QuestionCount,
		arg.StartsAt,
		arg.EndsAt,
	)
	var i Tournament
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.SubjectID,
		&i.QuestionCount,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedAt,
	)
	return i, err
}

const getTournament = `-- name: GetTournament :one
SELECT id, title, subject_id, question_count, starts_at, ends_at, created_at FROM tournaments WHERE id = $1
`

func (q *Queries) GetTournament(ctx context.Context, id uuid.UUID) (Tournament, error) {
	row := q.db.QueryRow(ctx, getTournament, id)
	var i Tournament
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.SubjectID,
		&i.QuestionCount,
		&i.StartsAt,
		&i.EndsAt,
		&i.CreatedAt,
	)
	return i, err
}

const listEntries = `-- name: ListEntries :many
SELECT te.score, u.username, te.user_id
FROM tournament_entries te
JOIN users u ON u.id = te.user_id
WHERE te.tournament_id = $1
ORDER BY te.score DESC, te.updated_at ASC
LIMIT 50
`

type ListEntriesRow struct {
	Score    int32     `json:"score"`
	Username *string   `json:"username"`
	UserID   uuid.UUID `json:"user_id"`
}

func (q *Queries) ListEntries(ctx context.Context, tournamentID uuid.UUID) ([]ListEntriesRow, error) {
	rows, err := q.db.Query(ctx, listEntries, tournamentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEntriesRow
	for rows.Next() {
		var i ListEntriesRow
		if err := rows.Scan(&i.Score, &i.Username, &i.UserID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTournaments = `-- name: ListTournaments :many
SELECT t.id, t.title, t.subject_id, t.question_count, t.starts_at, t.ends_at, t.created_at, s.slug AS subject_slug, s.name AS subject_name
FROM tournaments t
JOIN subjects s ON s.id = t.subject_id
ORDER BY t.starts_at DESC
`

type ListTournamentsRow struct {
	ID            uuid.UUID `json:"id"`
	Title         string    `json:"title"`
	SubjectID     uuid.UUID `json:"subject_id"`
	QuestionCount int32     `json:"question_count"`
	StartsAt      time.Time `json:"starts_at"`
	EndsAt        time.Time `json:"ends_at"`
	CreatedAt     time.Time `json:"created_at"`
	SubjectSlug   string    `json:"subject_slug"`
	SubjectName   string    `json:"subject_name"`
}

func (q *Queries) ListTournaments(ctx context.Context) ([]ListTournamentsRow, error) {
	rows, err := q.db.Query(ctx, listTournaments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTournamentsRow
	for rows.Next() {
		var i ListTournamentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.SubjectID,
			&i.QuestionCount,
			&i.StartsAt,
			&i.EndsAt,
			&i.CreatedAt,
			&i.SubjectSlug,
			&i.SubjectName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertEntry = `-- name: UpsertEntry :exec
INSERT INTO tournament_entries (tournament_id, user_id, score)
VALUES ($1, $2, $3)
ON CONFLICT (tournament_id, user_id)
DO UPDATE SET score = GREATEST(tournament_entries.score, EXCLUDED.score), updated_at = now()
`

type UpsertEntryParams struct {
	TournamentID uuid.UUID `json:"tournament_id"`
	UserID       uuid.UUID `json:"user_id"`
	Score        int32     `json:"score"`
}

// Eng yaxshi ball saqlanadi (GREATEST).
func (q *Queries) UpsertEntry(ctx context.Context, arg UpsertEntryParams) error {
	_, err := q.db.Exec(ctx, upsertEntry, arg.TournamentID, arg.UserID, arg.Score)
	return err
}
