// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO users (username, email, password_hash)
VALUES ($1, $2, $3)
RETURNING id, username, email, password_hash, telegram_id, is_guest, role, created_at
`

type CreateAccountParams struct {
	Username     *string `json:"username"`
	Email        *string `json:"email"`
	PasswordHash *string `json:"password_hash"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (User, error) {
	row := q.db.QueryRow(ctx, createAccount, arg.Username, arg.Email, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.TelegramID,
		&i.IsGuest,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const createGuest = `-- name: CreateGuest :one
INSERT INTO users (is_guest) VALUES (true)
RETURNING id, username, email, password_hash, telegram_id, is_guest, role, created_at
`

func (q *Queries) CreateGuest(ctx context.Context) (User, error) {
	row := q.db.QueryRow(ctx, createGuest)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.TelegramID,
		&i.IsGuest,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, password_hash, telegram_id, is_guest, role, created_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email *string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.TelegramID,
		&i.IsGuest,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, username, email, password_hash, telegram_id, is_guest, role, created_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.TelegramID,
		&i.IsGuest,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByTelegramID = `-- name: GetUserByTelegramID :one
SELECT id, username, email, password_hash, telegram_id, is_guest, role, created_at FROM users WHERE telegram_id = $1
`

func (q *Queries) GetUserByTelegramID(ctx context.Context, telegramID *int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByTelegramID, telegramID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.TelegramID,
		&i.IsGuest,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}
